trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'visitor-counter'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        pip install -r app/requirements.txt
      displayName: 'Install dependencies'

    - script: |
        VERSION=$(cat app/version.txt)
        echo "##vso[task.setvariable variable=VERSION]$VERSION"
      displayName: 'Read version from file'

    - task: Docker@2
      inputs:
        containerRegistry: 'spacelysprockets.azurecr.io'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: 'app/Dockerfile'
        tags: |
          $(VERSION)
      displayName: 'Build and Push Docker Image'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Deploying to staging...'
            displayName: 'Deploy to Staging'
