apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers:
  - name: counter
    image: spacelysprockets.azurecr.io/visitor-counter:latest
    ports:
    - containerPort: 5000
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
  imagePullSecrets:
  - name: acr-secret
  - name: acr-secret
