name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Set up Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    # Logs in with your Azure credentials using the JSON secret
    - name: Azure login
      uses: azure/login@v2.1.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Ensure storage account and container exist
      env:
        AZ_RG_NAME: "terraform-resource-group"
        AZ_STORAGE_ACCOUNT_NAME: "spacelybackendhd"
        AZ_CONTAINER_NAME: "tfstate"
        SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: |
        az group create --name $AZ_RG_NAME --location eastus --subscription $SUBSCRIPTION_ID || echo "Resource group already exists."
        if ! az storage account show --name $AZ_STORAGE_ACCOUNT_NAME --resource-group $AZ_RG_NAME --subscription $SUBSCRIPTION_ID; then
          az storage account create --name $AZ_STORAGE_ACCOUNT_NAME --resource-group $AZ_RG_NAME --location eastus --sku Standard_LRS --subscription $SUBSCRIPTION_ID
        fi
        AZ_STORAGE_KEY=$(az storage account keys list --resource-group $AZ_RG_NAME --account-name $AZ_STORAGE_ACCOUNT_NAME --query '[0].value' --output tsv --subscription $SUBSCRIPTION_ID)
        az storage container create --name $AZ_CONTAINER_NAME --account-name $AZ_STORAGE_ACCOUNT_NAME --account-key $AZ_STORAGE_KEY --subscription $SUBSCRIPTION_ID || echo "Container already exists."
        echo "AZ_STORAGE_KEY=$AZ_STORAGE_KEY" >> $GITHUB_ENV

    - name: Print Environment Variables
      run: |
        echo "AZ_RG_NAME=$AZ_RG_NAME"
        echo "AZ_STORAGE_ACCOUNT_NAME=$AZ_STORAGE_ACCOUNT_NAME"
        echo "AZ_CONTAINER_NAME=$AZ_CONTAINER_NAME"
        echo "SUBSCRIPTION_ID=$SUBSCRIPTION_ID"
        echo "AZ_STORAGE_KEY=$AZ_STORAGE_KEY"

    - name: Terraform Init
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_ACCESS_KEY: ${{ env.AZ_STORAGE_KEY }}
      working-directory: infra
      run: terraform init -backend-config="resource_group_name=${{ env.AZ_RG_NAME }}" -backend-config="storage_account_name=${{ env.AZ_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ env.AZ_CONTAINER_NAME }}" -backend-config="key=terraform.tfstate" -backend-config="access_key=${{ env.AZ_STORAGE_KEY }}"

    - name: Plan Terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      working-directory: infra
      run: terraform plan

    - name: Apply Terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      working-directory: infra
      run: terraform apply -auto-approve

    - name: Read version from file
      id: version
      run: echo "::set-output name=VERSION::$(cat app/version.txt)"

    - name: Build Docker image
      run: |
        docker build --build-arg VERSION=${{ steps.version.outputs.VERSION }} -t spacelysprockets.azurecr.io/visitor-counter:${{ steps.version.outputs.VERSION }} -f app/Dockerfile app

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login spacelysprockets.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Push Docker image to Azure Container Registry
      run: docker push spacelysprocketshd.azurecr.io/visitor-counter:${{ steps.version.outputs.VERSION }}
